runtime: go123

instance_class: F1

automatic_scaling:
  min_instances: 1
  max_instances: 1
  max_concurrent_requests: 50

handlers:
- url: /example/app/
  static_files: example/app/index.html
  upload: example/app/(.*)

- url: /.*
  script: auto
