// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exchange.proto

package apis

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateSessionRequest struct {
	SessionDescription   *SessionDescription `protobuf:"bytes,1,opt,name=session_description,json=sessionDescription,proto3" json:"session_description,omitempty"`
	SessionId            string              `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateSessionRequest) Reset()         { *m = CreateSessionRequest{} }
func (m *CreateSessionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSessionRequest) ProtoMessage()    {}
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{0}
}

func (m *CreateSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionRequest.Unmarshal(m, b)
}
func (m *CreateSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionRequest.Marshal(b, m, deterministic)
}
func (m *CreateSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionRequest.Merge(m, src)
}
func (m *CreateSessionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSessionRequest.Size(m)
}
func (m *CreateSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionRequest proto.InternalMessageInfo

func (m *CreateSessionRequest) GetSessionDescription() *SessionDescription {
	if m != nil {
		return m.SessionDescription
	}
	return nil
}

func (m *CreateSessionRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type CreateSessionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSessionResponse) Reset()         { *m = CreateSessionResponse{} }
func (m *CreateSessionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSessionResponse) ProtoMessage()    {}
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{1}
}

func (m *CreateSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionResponse.Unmarshal(m, b)
}
func (m *CreateSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionResponse.Marshal(b, m, deterministic)
}
func (m *CreateSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionResponse.Merge(m, src)
}
func (m *CreateSessionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSessionResponse.Size(m)
}
func (m *CreateSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionResponse proto.InternalMessageInfo

type GetSessionRequest struct {
	SessionId            string   `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSessionRequest) Reset()         { *m = GetSessionRequest{} }
func (m *GetSessionRequest) String() string { return proto.CompactTextString(m) }
func (*GetSessionRequest) ProtoMessage()    {}
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{2}
}

func (m *GetSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionRequest.Unmarshal(m, b)
}
func (m *GetSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionRequest.Marshal(b, m, deterministic)
}
func (m *GetSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionRequest.Merge(m, src)
}
func (m *GetSessionRequest) XXX_Size() int {
	return xxx_messageInfo_GetSessionRequest.Size(m)
}
func (m *GetSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionRequest proto.InternalMessageInfo

func (m *GetSessionRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type GetSessionResponse struct {
	SessionDescription   *SessionDescription `protobuf:"bytes,1,opt,name=session_description,json=sessionDescription,proto3" json:"session_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetSessionResponse) Reset()         { *m = GetSessionResponse{} }
func (m *GetSessionResponse) String() string { return proto.CompactTextString(m) }
func (*GetSessionResponse) ProtoMessage()    {}
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{3}
}

func (m *GetSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionResponse.Unmarshal(m, b)
}
func (m *GetSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionResponse.Marshal(b, m, deterministic)
}
func (m *GetSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionResponse.Merge(m, src)
}
func (m *GetSessionResponse) XXX_Size() int {
	return xxx_messageInfo_GetSessionResponse.Size(m)
}
func (m *GetSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionResponse proto.InternalMessageInfo

func (m *GetSessionResponse) GetSessionDescription() *SessionDescription {
	if m != nil {
		return m.SessionDescription
	}
	return nil
}

type DeleteSessionRequest struct {
	SessionId            string   `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSessionRequest) Reset()         { *m = DeleteSessionRequest{} }
func (m *DeleteSessionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSessionRequest) ProtoMessage()    {}
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{4}
}

func (m *DeleteSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSessionRequest.Unmarshal(m, b)
}
func (m *DeleteSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSessionRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSessionRequest.Merge(m, src)
}
func (m *DeleteSessionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSessionRequest.Size(m)
}
func (m *DeleteSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSessionRequest proto.InternalMessageInfo

func (m *DeleteSessionRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type DeleteSessionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSessionResponse) Reset()         { *m = DeleteSessionResponse{} }
func (m *DeleteSessionResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSessionResponse) ProtoMessage()    {}
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{5}
}

func (m *DeleteSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSessionResponse.Unmarshal(m, b)
}
func (m *DeleteSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSessionResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSessionResponse.Merge(m, src)
}
func (m *DeleteSessionResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSessionResponse.Size(m)
}
func (m *DeleteSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSessionResponse proto.InternalMessageInfo

type SessionDescription struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Sdp                  string   `protobuf:"bytes,2,opt,name=sdp,proto3" json:"sdp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionDescription) Reset()         { *m = SessionDescription{} }
func (m *SessionDescription) String() string { return proto.CompactTextString(m) }
func (*SessionDescription) ProtoMessage()    {}
func (*SessionDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{6}
}

func (m *SessionDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionDescription.Unmarshal(m, b)
}
func (m *SessionDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionDescription.Marshal(b, m, deterministic)
}
func (m *SessionDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionDescription.Merge(m, src)
}
func (m *SessionDescription) XXX_Size() int {
	return xxx_messageInfo_SessionDescription.Size(m)
}
func (m *SessionDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionDescription.DiscardUnknown(m)
}

var xxx_messageInfo_SessionDescription proto.InternalMessageInfo

func (m *SessionDescription) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SessionDescription) GetSdp() string {
	if m != nil {
		return m.Sdp
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateSessionRequest)(nil), "apis.CreateSessionRequest")
	proto.RegisterType((*CreateSessionResponse)(nil), "apis.CreateSessionResponse")
	proto.RegisterType((*GetSessionRequest)(nil), "apis.GetSessionRequest")
	proto.RegisterType((*GetSessionResponse)(nil), "apis.GetSessionResponse")
	proto.RegisterType((*DeleteSessionRequest)(nil), "apis.DeleteSessionRequest")
	proto.RegisterType((*DeleteSessionResponse)(nil), "apis.DeleteSessionResponse")
	proto.RegisterType((*SessionDescription)(nil), "apis.SessionDescription")
}

func init() { proto.RegisterFile("exchange.proto", fileDescriptor_e0328a4f16f87ea1) }

var fileDescriptor_e0328a4f16f87ea1 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xdd, 0x4a, 0x32, 0x51,
	0x14, 0x65, 0x54, 0x04, 0xf7, 0x87, 0x9f, 0x7e, 0xfb, 0xb3, 0x1c, 0xc6, 0x9f, 0x6c, 0x28, 0x10,
	0x2f, 0x1c, 0x30, 0xba, 0xf1, 0xae, 0x32, 0xc2, 0xab, 0x60, 0xbc, 0xeb, 0x46, 0x26, 0x67, 0xab,
	0x53, 0x32, 0x67, 0x9a, 0x33, 0xfd, 0x11, 0x41, 0xf4, 0x0a, 0xbd, 0x51, 0xaf, 0xd0, 0x2b, 0xf4,
	0x20, 0xe1, 0x99, 0x23, 0x93, 0xce, 0x88, 0x10, 0xdd, 0x0d, 0x7b, 0xcf, 0x5a, 0x6b, 0xaf, 0xb5,
	0x38, 0xf0, 0x97, 0x1e, 0x46, 0x53, 0xcb, 0x9d, 0x50, 0xdb, 0xf3, 0x59, 0xc0, 0x30, 0x63, 0x79,
	0x0e, 0xd7, 0xaa, 0x13, 0xc6, 0x26, 0x33, 0x32, 0x2c, 0xcf, 0x31, 0x2c, 0xd7, 0x65, 0x81, 0x15,
	0x38, 0xcc, 0xe5, 0xe1, 0x3f, 0xfa, 0x8b, 0x02, 0xa5, 0x13, 0x9f, 0xac, 0x80, 0x06, 0xc4, 0xb9,
	0xc3, 0x5c, 0x93, 0x6e, 0x6e, 0x89, 0x07, 0xd8, 0x87, 0xff, 0x3c, 0x9c, 0x0c, 0x6d, 0xe2, 0x23,
	0xdf, 0xf1, 0xe6, 0x30, 0x55, 0x69, 0x28, 0xcd, 0x3f, 0x1d, 0xb5, 0x3d, 0xa7, 0x6e, 0x4b, 0x48,
	0x2f, 0xda, 0x9b, 0xc8, 0x63, 0x33, 0xac, 0x01, 0x2c, 0xa8, 0x1c, 0x5b, 0x4d, 0x35, 0x94, 0x66,
	0xce, 0xcc, 0xc9, 0x49, 0xdf, 0xd6, 0xcb, 0xb0, 0xb5, 0x72, 0x01, 0xf7, 0x98, 0xcb, 0x49, 0xef,
	0xc0, 0xbf, 0x33, 0x0a, 0x56, 0xee, 0xda, 0x40, 0x36, 0x04, 0xfc, 0x8e, 0x09, 0x99, 0x7e, 0xd1,
	0x8c, 0x7e, 0x08, 0xa5, 0x1e, 0xcd, 0x28, 0x96, 0xd7, 0x66, 0x93, 0x2b, 0x30, 0x69, 0xb2, 0x0b,
	0x18, 0x57, 0x46, 0x84, 0x4c, 0xf0, 0xe8, 0x91, 0xb8, 0x30, 0x67, 0x8a, 0x6f, 0x2c, 0x42, 0x9a,
	0xdb, 0x9e, 0xa4, 0x9e, 0x7f, 0x76, 0xde, 0xd3, 0x50, 0x38, 0x95, 0x9d, 0x0f, 0xc8, 0xbf, 0x73,
	0x46, 0x84, 0xd7, 0x90, 0x5f, 0x4a, 0x13, 0xb5, 0xd0, 0x5e, 0x52, 0xc9, 0x5a, 0x25, 0x71, 0x27,
	0x2f, 0xdb, 0x7d, 0xfd, 0xf8, 0x7c, 0x4b, 0x55, 0xf4, 0x6d, 0x43, 0xda, 0xe0, 0xc6, 0x53, 0x64,
	0xf1, 0xb9, 0xab, 0xb4, 0x70, 0x06, 0xc5, 0x28, 0xed, 0x23, 0x97, 0xdf, 0x93, 0x8f, 0xe5, 0x90,
	0x33, 0xd6, 0x9c, 0xa6, 0xc6, 0x17, 0x52, 0x69, 0x5f, 0x28, 0xed, 0x60, 0x2d, 0x59, 0xc9, 0xb0,
	0x42, 0xe6, 0x2b, 0x28, 0x44, 0xe0, 0xf3, 0xf1, 0xf8, 0x67, 0x62, 0x7b, 0x42, 0xac, 0x8e, 0xd5,
	0x35, 0x62, 0x4c, 0x10, 0x4f, 0x21, 0xbf, 0xd4, 0xd7, 0x22, 0xc6, 0xa4, 0xee, 0x17, 0x31, 0x26,
	0x17, 0x5c, 0x17, 0x7a, 0x6a, 0x6b, 0x4d, 0x8c, 0xc7, 0xd9, 0x0b, 0xf1, 0x4e, 0x2f, 0xb3, 0xe2,
	0x41, 0x1e, 0x7c, 0x05, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xce, 0x42, 0xeb, 0xc6, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExchangeServiceClient is the client API for ExchangeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExchangeServiceClient interface {
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	GetSessionAnswer(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	GetSessionOffer(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
}

type exchangeServiceClient struct {
	cc *grpc.ClientConn
}

func NewExchangeServiceClient(cc *grpc.ClientConn) ExchangeServiceClient {
	return &exchangeServiceClient{cc}
}

func (c *exchangeServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, "/apis.ExchangeService/CreateSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeServiceClient) GetSessionAnswer(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, "/apis.ExchangeService/GetSessionAnswer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeServiceClient) GetSessionOffer(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, "/apis.ExchangeService/GetSessionOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, "/apis.ExchangeService/DeleteSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExchangeServiceServer is the server API for ExchangeService service.
type ExchangeServiceServer interface {
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	GetSessionAnswer(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	GetSessionOffer(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
}

func RegisterExchangeServiceServer(s *grpc.Server, srv ExchangeServiceServer) {
	s.RegisterService(&_ExchangeService_serviceDesc, srv)
}

func _ExchangeService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.ExchangeService/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExchangeService_GetSessionAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServiceServer).GetSessionAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.ExchangeService/GetSessionAnswer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServiceServer).GetSessionAnswer(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExchangeService_GetSessionOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServiceServer).GetSessionOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.ExchangeService/GetSessionOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServiceServer).GetSessionOffer(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExchangeService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.ExchangeService/DeleteSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExchangeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apis.ExchangeService",
	HandlerType: (*ExchangeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _ExchangeService_CreateSession_Handler,
		},
		{
			MethodName: "GetSessionAnswer",
			Handler:    _ExchangeService_GetSessionAnswer_Handler,
		},
		{
			MethodName: "GetSessionOffer",
			Handler:    _ExchangeService_GetSessionOffer_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _ExchangeService_DeleteSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exchange.proto",
}
